// imageAssets.js

const images = {
    "DisneylandRailroadDiscoverylandStation.jpg": require('../assets/DisneylandRailroadDiscoverylandStation.jpg'),
    "DisneylandRailroadFantasylandStation.jpg": require('../assets/DisneylandRailroadFantasylandStation.jpg'),
    "DisneylandRailroadMainStreetStation.jpg": require('../assets/DisneylandRailroadMainStreetStation.jpg'),
    "DisneylandRailroad.jpg": require('../assets/DisneylandRailroad.jpg'),
    "Orbitron.jpg": require('../assets/Orbitron.jpg'),
    "MeetMickeyMouse.jpg": require('../assets/MeetMickeyMouse.jpg'),
    "FrontierlandPlayground.jpg": require('../assets/FrontierlandPlayground.jpg'),
    "DisneylandRailroadFrontierlandDepot.jpg": require('../assets/DisneylandRailroadFrontierlandDepot.jpg'),
    "PirateGalleon.jpg": require('../assets/PirateGalleon.jpg'),
    "IndianaJonesandtheTempleofPeril.jpg": require('../assets/IndianaJonesandtheTempleofPeril.jpg'),
    "LaCabanedesRobinson.jpg": require('../assets/LaCabanedesRobinson.jpg'),
    "BigThunderMountain.jpg": require('../assets/BigThunderMountain.jpg'),
    "MadHattersTeaCups.jpg": require('../assets/MadHattersTeaCups.jpg'),
    "LesVoyagesdePinocchio.jpg": require('../assets/LesVoyagesdePinocchio.jpg'),
    "CaseyJrlePetitTrainduCirque.jpg": require('../assets/CaseyJrlePetitTrainduCirque.jpg'),
    "PhantomManor.jpg": require('../assets/PhantomManor.jpg'),
    "StarWarsHyperspaceMountain.jpg": require('../assets/StarWarsHyperspaceMountain.jpg'),
    "StarTourstheAdventuresContinue.jpg": require('../assets/StarToursTheAdventuresContinue.jpg'),
    "ThunderMesaRiverboatLanding.jpg": require('../assets/ThunderMesaRiverboatLanding.jpg'),
    "AlicesCuriousLabyrinth.jpg": require('../assets/AlicesCuriousLabyrinth.jpg'),
    "BuzzLightyearLaserBlast.jpg": require('../assets/BuzzLightyearLaserBlast.jpg'),
    "MainStreetVehicles.jpg": require('../assets/MainStreetVehicles.jpg'),
    "PeterPansFlight.jpg": require('../assets/PeterPansFlight.jpg'),
    "PrincessPavilion.jpg": require('../assets/PrincessPavilion.jpg'),
    "DumbotheFlyingElephant.jpg": require('../assets/DumbotheFlyingElephant.jpg'),
    "LePassageEnchantedAladdin.jpg": require('../assets/LePassageEnchantedAladdin.jpg'),
    "AutopiapresentedbyAvis.jpg": require('../assets/AutopiapresentedbyAvis.jpg'),
    "LeCarrouseldelancelot.jpg": require('../assets/LeCarrouseldeLancelot.jpg'),
    "LesMystèresduNautilus.jpg": require('../assets/LesMysteresduNautilus.jpg'),
    "LaTanièreduDragon.jpg": require('../assets/LaTaniereduDragon.jpg'),
    "RustlerRoundupShootinGallery.jpg": require('../assets/RustlerRoundupShootinGallery.jpg'),
    "AdventureIsle.jpg": require('../assets/AdventureIsle.jpg'),
    "welcometostarportastarwarsencounter.jpg": require('../assets/WelcometoStarportAStarWarsEncounter.jpg'),
    "BlancheNeigeetlesSeptNains.jpg": require('../assets/BlancheNeigeetlesSeptNains.jpg'),
    "MickeysPhilharMagic.jpg": require('../assets/MickeysPhilharMagic.jpg'),
    "PiratesoftheCaribbean.jpg": require('../assets/PiratesoftheCaribbean.jpg'),
    "itsasmallworld.jpg": require('../assets/itsasmallworld.jpg'),
    "LePaysdesContesdeFées.jpg": require('../assets/LePaysdesContesdeFees.jpg'),
    "PiratesBeach.jpg": require('../assets/PiratesBeach.jpg'),
    "AvengersAssembleFlightForce.jpg": require('../assets/AvengersAssembleFlightForce.jpg'),
    "CarsROADTRIP.jpg": require('../assets/CarsROADTRIP.jpg'),
    "SpiderManWEBAdventure.jpg": require('../assets/SpiderManWEBAdventure.jpg'),
    "CarsQuatreRouesRallye.jpg": require('../assets/CarsQuatreRouesRallye.jpg'),
    "ToySoldiersParachuteDrop.jpg": require('../assets/ToySoldiersParachuteDrop.jpg'),
    "RCRacer.jpg": require('../assets/RCRacer.jpg'),
    "TheTwilightZoneTowerofTerror.jpg": require('../assets/TheTwilightZoneTowerofTerror.jpg'),
    "CrushsCoaster.jpg": require('../assets/CrushsCoaster.jpg'),
    "RatatouilleTheAdventure.jpg": require('../assets/RatatouilleTheAdventure.jpg'),
    "SlinkyDogZigzagSpin.jpg": require('../assets/SlinkyDogZigzagSpin.jpg'),
    "LesTapisVolantsFlyingCarpetsOverAgrabah.jpg": require('../assets/LesTapisVolantsFlyingCarpetsOverAgrabah.jpg'),
    "default.jpg": require('../assets/default.jpg')
};

export default images;
