const RestaurantsImages = {
    'CoolPost.jpg': require('../assets/CoolPost.jpg'),
    'TheCoffeeGrinder.jpg': require('../assets/TheCoffeeGrinder.jpg'),
    'CookieKitchen.jpg': require('../assets/CookieKitchen.jpg'),
    'RestaurantHakunaMatata.jpg': require('../assets/RestaurantHakunaMatata.jpg'),
    'CoolStation.jpg': require('../assets/CoolStation.jpg'),
    'CableCarBakeShop.jpg': require('../assets/CableCarBakeShop.jpg'),
    'MarketHouseDeli.jpg': require('../assets/MarketHouseDeli.jpg'),
    'PlazaGardensRestaurant.jpg': require('../assets/PlazaGardensRestaurant.jpg'),
    'VictoriasHomeStyleRestaurant.jpg': require('../assets/VictoriasHomeStyleRestaurant.jpg'),
    'WaltsanAmericanrestaurant.jpg': require('../assets/WaltsAnAmericanRestaurant.jpg'),
    'PizzeriaBellaNotte.jpg': require('../assets/PizzeriaBellaNotte.jpg'),
    'LArbreEnchante.jpg': require('../assets/LArbreEnchante.jpg'),
    'AubergedeCendrillon.jpg': require('../assets/AubergeDeCendrillon.jpg'),
    'AuChaletdelaMarionnette.jpg': require('../assets/AuChaletDeLaMarionnette.jpg'),
    'MarchHareRefreshments.jpg': require('../assets/MarchHareRefreshments.jpg'),
    'LastChanceCafe.jpg': require('../assets/LastChanceCafe.jpg'),
    'TheLuckyNuggetSaloon.jpg': require('../assets/TheLuckyNuggetSaloon.jpg'),
    'SilverSpurSteakhouse.jpg': require('../assets/SilverSpurSteakhouse.jpg'),
    'ColonelHathisOutpostRestaurant.jpg': require('../assets/ColonelHathisOutpostRestaurant.jpg'),
    'RocketCafe.jpg': require('../assets/RocketCafe.jpg'),
    'CritterCorral.jpg': require('../assets/CritterCorral.jpg'),
    'CafedelaBrousse.jpg': require('../assets/CafeDeLaBrousse.jpg'),
    'CafeHyperion.jpg': require('../assets/CafeHyperion.jpg'),
    'ToadHallRestaurant.jpg': require('../assets/ToadHallRestaurant.jpg'),
    'CowboyCookoutBarbecue.jpg': require('../assets/CowboyCookoutBarbecue.jpg'),
    'CaptainJacksRestaurantdesPirates.jpg': require('../assets/CaptainJacksRestaurantDesPirates.jpg'),
    'CaseysCorner.jpg': require('../assets/CaseysCorner.jpg'),
    'TheGibsonGirlIceCreamParlour.jpg': require('../assets/TheGibsonGirlIceCreamParlour.jpg'),
    'TheIceCreamCompany.jpg': require('../assets/TheIceCreamCompany.jpg'),
    'TheOldMill.jpg': require('../assets/TheOldMill.jpg'),
    'CasadeCocoRestaurantedeFamilia.jpg': require('../assets/CasaDeCocoRestauranteDeFamilia.jpg'),
    'AgrabahCafeRestaurant.jpg': require('../assets/AgrabahCafeRestaurant.jpg'),
    'CharacterDiningatPlazaGardensRestaurant.jpg': require('../assets/CharacterDiningAtPlazaGardensRestaurant.jpg'),
    'SpecialityIceCream.jpg': require('../assets/SpecialityIceCream.jpg'),
    'StarkFactory.jpg': require('../assets/StarkFactory.jpg'),
    'PYMKitchen.jpg': require('../assets/PYMKitchen.jpg'),
    'BistrotChezRemy.jpg': require('../assets/BistrotChezRemy.jpg'),
    'SuperDiner.jpg': require('../assets/SuperDiner.jpg'),
    'FANtasticFoodTruck.jpg': require('../assets/FANtasticFoodTruck.jpg'),
    'WEBFoodTruck.jpg': require('../assets/WEBFoodTruck.jpg'),
    'ToonStudioCateringCo.jpg': require('../assets/ToonStudioCateringCo.jpg'),
    'IceCreamCreations.jpg': require('../assets/IceCreamCreations.jpg'),
    'LaughNGo.jpg': require('../assets/LaughNGo.jpg'),
    "default.jpg": require('../assets/default.jpg')
};

export default RestaurantsImages;
