platform :ios, '12.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MagicJourny' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MagicJournyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Ajout du pod react-native-background-fetch
  pod 'react-native-background-fetch', :path => '../node_modules/react-native-background-fetch'

  post_install do |installer|
    react_native_post_install(installer)
  end
end
